typography_spectrum: 0.7530831580469846
content_rating:
  adult: false
color:
  saturation: 0.9770588033678619
  brandStrength: 0.40887985042951047
  lightness: 0.3221317872739775
  brandColors:
    - '#FFFFFF'
    - '#00A6D0'
    - '#266D7F'
    - '#63C7D8'
    - '#F4FBFD'
  rhythmicContrast: 0.5055844760960946
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8103083185177519
analytics:
  twitter: null
  google: null
  facebook: null
logo: null
name: Spotless of Utah
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Us
    id: f9a33562-5f49-4e51-95e9-c68ac47cdf9e
    type: content
  - name: Contact us
    url: 'http://blueox.co/contact.php'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Experts in Commercial Cleaning
content: []
description: >-
  Providing Janitorial services in your local Utah area - Logan, Brigham city,
  and Ogden
purpose:
  - type: contact
    url: 'tel:4358819189'
    label: Call 435.881.9189
  - type: contact
    url: 'mailto:info@spotlssofutah.com'
    label: Contact us
