name: Spotlessofutah
favicon: null
layout_spectrum: 0.33152131270617247
typography_spectrum: 0.8782811036799103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9145596807356924
  lightness: 0.8313094254117459
  saturation: 0.5784826567396522
  rhythmicContrast: 0.7228588552679867
purpose: []
