layout_spectrum: 0.26210146860007455
typography_spectrum: 0.660996239534072
color:
  saturation: 0.2908516683390751
  brandStrength: 0.2872919466385231
  lightness: 0.8225058023557804
  brandColors:
    - '#FFFFFF'
    - '#00A6D0'
    - '#266D7F'
    - '#63C7D8'
    - '#F4FBFD'
  rhythmicContrast: 0.911012016401285
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/950a5892-2a30-431a-a9a3-8525850438ac.png
name: ' '
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Contact us
    url: 'http://blueox.co/contact.php'
    type: external
  - name: Services
    url: 'http://blueox.co/services.php'
    type: external
  - name: Quote
    url: 'http://blueox.co/quote.php'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Experts in Commercial Cleaning
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff457417-2da7-4bb4-b51b-569f8549b49b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff457417-2da7-4bb4-b51b-569f8549b49b.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0107d94a-275a-4b3b-914f-f0795477bf84.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0107d94a-275a-4b3b-914f-f0795477bf84.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac2aaa1a-89ad-4937-89b2-99486844de26.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ac2aaa1a-89ad-4937-89b2-99486844de26.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/718579f7-0edb-4d1b-8715-9c38ee738a22.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/718579f7-0edb-4d1b-8715-9c38ee738a22.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Providing Janitorial services in your local Utah area - Logan, Brigham city,
  and Ogden
purpose:
  - type: contact
    url: 'tel:4358819189'
    label: Call 435.881.9189
  - type: contact
    url: 'mailto:info@spotlssofutah.com'
    label: Contact us
