layout_spectrum: 0.8103083185177519
typography_spectrum: 0.7530831580469846
color:
  saturation: 0.9770588033678619
  brandStrength: 0.40887985042951047
  lightness: 0.3221317872739775
  brandColors:
    - '#FFFFFF'
    - '#00A6D0'
    - '#266D7F'
    - '#63C7D8'
    - '#F4FBFD'
  rhythmicContrast: 0.5055844760960946
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: ' '
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Us
    id: f9a33562-5f49-4e51-95e9-c68ac47cdf9e
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Experts in Commercial Cleaning
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c632f8cf-b32a-40e9-806a-0d709cbc9a09.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c632f8cf-b32a-40e9-806a-0d709cbc9a09.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'tel:4358819189'
    label: Call 435.881.9189
  - type: contact
    url: 'mailto:info@spotlssofutah.com'
    label: Email us for a quote
github: true
logo: null
content_rating:
  adult: false
