layout_spectrum: 0.4678024172251768
typography_spectrum: 0.758481818334301
color:
  saturation: 0.688392424624653
  brandStrength: 0.6905643116287186
  lightness: 0.7403923497573094
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  rhythmicContrast: 0.8721674868646124
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: ' '
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About Us
    id: f9a33562-5f49-4e51-95e9-c68ac47cdf9e
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Commercial Office Cleaning Services by Spotless
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2652725-c6eb-48ac-a5ed-9a6684e103cf.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e2652725-c6eb-48ac-a5ed-9a6684e103cf.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/60c7e2df-7c25-4182-b39a-e8db3d0df9bd.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/60c7e2df-7c25-4182-b39a-e8db3d0df9bd.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: THE TIDY UPKEEP OF YOUR OFFICE REFLECTS ON YOUR BUSINESS. WE'LL MAKE IT SHINE.
purpose:
  - type: contact
    url: 'tel:435.881.9189'
    label: Call 435.881.9189
  - type: contact
    url: 'mailto:info@spotlssofutah.com'
    label: Email us
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/317e0a0d-67f3-415b-8cda-fb01ac1e2968.png
content_rating:
  adult: false
