name: Spotlessofutah
favicon: null
layout_spectrum: 0.48808
typography_spectrum: 0.84893
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d98d4'
    - '#000000'
    - '#ffffff'
    - '#196a35'
    - '#a7dff9'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
